Made formatting changes to task 2 step 13 onwards
oracle-livelabs/em-omc pull request #27
Opened 2022-08-01 22:52 UTC by shppra

2022-08-01 22:55 UTC, shppra commented
Made formatting changes to task 2 step 13 onwards

2022-08-02 00:38 UTC, arabellayao requested changes
Hi! Please include workshop’s WMS in the title of the PR

2022-08-02 01:13 UTC, shppra reviewed
WMS ID: 1700 - Hybrid Database Configuration and Compliance Management]

2022-08-02 01:24 UTC, arabellayao approved these changes

2022-08-02 01:24 UTC, merged