9501 Kubernetes Monitoring and Troubleshooting
oracle-livelabs/em-omc pull request #291
Opened 2024-08-16 09:31 UTC by vikrredd

# 9501

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2024-08-16 10:35 UTC, ramonamagadan18 requested changes
Hi @vikrredd ! The compartment name and root name is visible in:

- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/cw-la-dashboards.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/cw24-la-compartment.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/dashboards-home.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/kubernetes-cluster-summary-widgets.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/kubernetes-cluster-summary.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/oke-cw24-kubernetes-cluster-field.png
- logging-analytics/oke-monitoring-la/next-steps-for-more-details/images/scope-filter-panel-kubernetes-cluster-summary.png

Please make sure that are hided.

2024-08-20 07:23 UTC, vikrredd commented
@ramonamagadan18 : I checked with our PM on the compartment being displayed. Since the compartments (emdemo(root) & CW24_Logging_Analytics) in screenshots have to used by customers they need to be shown. Also we have restricted the usage to the these compartments with policies, thus we should be fine. Thanks.

2024-08-20 07:46 UTC, anacoman11 approved these changes

2024-08-20 07:47 UTC, ramonamagadan18 approved these changes

2024-08-20 07:47 UTC, merged