Adding lab Ops Insights for HeatWave MySQL
oracle-livelabs/em-omc pull request #310
Opened 2024-10-21 18:43 UTC by SindhujaReddy-VT

Adding lab Ops Insights for HeatWave MySQL

WMS ID: 11543

- [ Yes] All filenames are lower case (including folders, images, files, etc.)
- [ Yes] Filenames are descriptive
- [ Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Yes ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Yes] Image references in markdown contain an alternate text

2024-10-21 18:45 UTC, SindhujaReddy-VT commented
I am a new Product Manager for HeatWave MySQL and have not been added to WMS ID:11543 and workflow management system yet. Please kindly approve the PR.

2024-10-23 09:17 UTC, anacoman11 requested changes
Hi @SindhujaReddy-VT, please blur the compartment from: 

- opsi-demo-mode-on.png
- employeesdb-database.png
- database-cpu2.png
- database-capacity-planning.png
- database-capacity-planning-mysql.png

2024-10-23 20:55 UTC, SindhujaReddy-VT commented
> Hi @SindhujaReddy-VT, please blur the compartment from:
> 
> * opsi-demo-mode-on.png
> * employeesdb-database.png
> * database-cpu2.png
> * database-capacity-planning.png
> * database-capacity-planning-mysql.png
> 
> Also, please update the Last Updated By/Date field from the Acknowledgements section for all updated files

Hi @anacoman11,
I updated the Last Updated By/Date field from the Acknowledgements section for all updated files (i.e.,**introduction.md file**)

Regarding the screenshots mentioned, I am not using any of our compartments for the simulation. It is in **Demo Mode**, enabled to showcase the simulations, and will remain the same for all users. For this reason, I did not blur the compartment name. I hope this clarifies!

Thank you!

2024-10-24 06:52 UTC, anacoman11 approved these changes

2024-10-24 06:53 UTC, merged